### ISSUE TITLE
Duna you're getting into Doom eh?

### ISSUE THREAD

**Issue by razzius** [gbgylfa/.doom.d#1]
Let me know if it works out for you :) I started on doom was overwhelmed and went back to vanilla emacs

**Comment by gbgylfa** [comment]
I've been using it for a little while already, I'm just setting up a repo
so I can sync to my new work machine. I've never actually used vanilla
emacs! I am not using even 5% of the functionality of doom, but I love the
vim keybindings, org mode, and the easy folder navigation. I was playing
around some with magit too.
